-- BEAUTYBOOK connected MVP schema
create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text, phone text, role text not null default 'customer'
 check(role in ('customer','professional','seller','admin')),
 language text not null default 'en', created_at timestamptz default now()
);
create table if not exists public.businesses (
 id bigint generated by default as identity primary key,
 owner_id uuid not null references public.profiles(id) on delete cascade,
 name text not null, business_type text not null check(business_type in ('beauty','fashion','both')),
 category text not null, location text, whatsapp text, verified boolean default false,
 active boolean default true, created_at timestamptz default now()
);
create table if not exists public.services (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.businesses(id) on delete cascade,
 name text not null, price_cfa integer not null check(price_cfa>=0),
 duration_minutes integer default 60, active boolean default true, created_at timestamptz default now()
);
create table if not exists public.products (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.businesses(id) on delete cascade,
 name text not null, category text not null, description text, price_cfa integer not null check(price_cfa>=0),
 stock integer not null default 0 check(stock>=0), sizes text[], image_url text,
 active boolean default true, created_at timestamptz default now()
);
create table if not exists public.bookings (
 id bigint generated by default as identity primary key,
 customer_id uuid not null references public.profiles(id) on delete cascade,
 business_id bigint not null references public.businesses(id),
 service_id bigint not null references public.services(id),
 booking_date date not null, booking_time time not null,
 status text not null default 'pending' check(status in ('pending','confirmed','completed','cancelled')),
 created_at timestamptz default now()
);
create table if not exists public.favorites (
 user_id uuid references public.profiles(id) on delete cascade,
 product_id bigint references public.products(id) on delete cascade,
 created_at timestamptz default now(), primary key(user_id,product_id)
);
create table if not exists public.reviews (
 id bigint generated by default as identity primary key,
 customer_id uuid not null references public.profiles(id) on delete cascade,
 business_id bigint not null references public.businesses(id) on delete cascade,
 rating integer not null check(rating between 1 and 5), comment text, created_at timestamptz default now()
);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$
begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.businesses enable row level security;
alter table public.services enable row level security;
alter table public.products enable row level security;
alter table public.bookings enable row level security;
alter table public.favorites enable row level security;
alter table public.reviews enable row level security;

-- Public catalog
create policy "public businesses read" on public.businesses for select to anon,authenticated using(active=true);
create policy "public services read" on public.services for select to anon,authenticated using(active=true);
create policy "public products read" on public.products for select to anon,authenticated using(active=true);
create policy "public reviews read" on public.reviews for select to anon,authenticated using(true);

-- Own profile
create policy "profile own read" on public.profiles for select to authenticated using((select auth.uid())=id);
create policy "profile own update" on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);

-- Business owner writes
create policy "business owner insert" on public.businesses for insert to authenticated with check((select auth.uid())=owner_id);
create policy "business owner update" on public.businesses for update to authenticated using((select auth.uid())=owner_id) with check((select auth.uid())=owner_id);
create policy "service owner insert" on public.services for insert to authenticated with check(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())));
create policy "service owner update" on public.services for update to authenticated using(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())));
create policy "product owner insert" on public.products for insert to authenticated with check(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())));
create policy "product owner update" on public.products for update to authenticated using(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())));

-- Booking privacy
create policy "customer booking read" on public.bookings for select to authenticated using((select auth.uid())=customer_id or exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())));
create policy "customer booking insert" on public.bookings for insert to authenticated with check((select auth.uid())=customer_id);
create policy "customer booking update" on public.bookings for update to authenticated using((select auth.uid())=customer_id or exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())));

create policy "favorite own read" on public.favorites for select to authenticated using((select auth.uid())=user_id);
create policy "favorite own insert" on public.favorites for insert to authenticated with check((select auth.uid())=user_id);
create policy "favorite own delete" on public.favorites for delete to authenticated using((select auth.uid())=user_id);
create policy "review own insert" on public.reviews for insert to authenticated with check((select auth.uid())=customer_id);

-- Grants
grant select on public.businesses,public.services,public.products,public.reviews to anon;
grant select,insert,update,delete on public.profiles,public.businesses,public.services,public.products,public.bookings,public.favorites,public.reviews to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- Product image bucket. Public catalog images are intentionally public.
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do update set public=true;
create policy "public product image read" on storage.objects for select to public using(bucket_id='product-images');
create policy "authenticated product image upload" on storage.objects for insert to authenticated
with check(bucket_id='product-images' and (storage.foldername(name))[1]=(select auth.uid())::text);
