-- ===== BEAUTYBOOK STAGE 1 additions =====
alter table public.businesses add column if not exists bio text;

create table if not exists public.availability_rules (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.businesses(id) on delete cascade,
 weekday smallint not null check (weekday between 1 and 7),
 start_time time not null,
 end_time time not null,
 slot_minutes integer not null default 60 check(slot_minutes between 15 and 480),
 active boolean not null default true,
 check(end_time > start_time)
);
create table if not exists public.notifications (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 title_en text not null, title_fr text not null,
 body_en text not null, body_fr text not null,
 type text not null default 'general', read_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.payments (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 booking_id bigint references public.bookings(id) on delete set null,
 provider text not null default 'pay_later',
 amount_cfa integer not null check(amount_cfa >= 0),
 status text not null default 'pending' check(status in ('pending','processing','paid','failed','cancelled')),
 external_reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists one_active_booking_per_slot
on public.bookings(business_id, booking_date, booking_time)
where status in ('pending','confirmed');

alter table public.availability_rules enable row level security;
alter table public.notifications enable row level security;
alter table public.payments enable row level security;
create policy "availability public read" on public.availability_rules for select to anon,authenticated using(active=true);
create policy "availability owner write" on public.availability_rules for all to authenticated
using(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())))
with check(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())));
create policy "notification own read" on public.notifications for select to authenticated using(user_id=(select auth.uid()));
create policy "notification own update" on public.notifications for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "payment own read" on public.payments for select to authenticated using(user_id=(select auth.uid()));

grant select on public.availability_rules to anon;
grant select,insert,update,delete on public.availability_rules,public.notifications,public.payments to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.notify_booking_change() returns trigger language plpgsql security definer set search_path=public as $$
declare owner uuid;
begin
 select owner_id into owner from businesses where id=new.business_id;
 if tg_op='INSERT' then
   insert into notifications(user_id,title_en,title_fr,body_en,body_fr,type)
   values(owner,'New booking','Nouvelle réservation','You received a new booking.','Vous avez reçu une nouvelle réservation.','booking_new');
 elsif old.status is distinct from new.status then
   insert into notifications(user_id,title_en,title_fr,body_en,body_fr,type)
   values(new.customer_id,'Booking updated','Réservation mise à jour','Your booking status changed to '||new.status||'.','Le statut de votre réservation est maintenant '||new.status||'.','booking_status');
 end if;
 return new;
end $$;
drop trigger if exists beautybook_booking_notifications on public.bookings;
create trigger beautybook_booking_notifications after insert or update of status on public.bookings
for each row execute function public.notify_booking_change();
