import 'package:flutter/widgets.dart';
class L {
  final Locale locale; const L(this.locale);
  static L of(BuildContext c)=>L(Localizations.localeOf(c));
  static const supported=[Locale('en'),Locale('fr')];
  static const _v=<String,Map<String,String>>{
    'en':{'app':'BEAUTYBOOK','home':'Home','shop':'Shop','bookings':'Bookings','sell':'Sell','profile':'Profile','professionals':'Beauty professionals','fashion':'Fashion marketplace','notifications':'Notifications','login':'Log in','signup':'Create account','email':'Email','password':'Password','logout':'Log out','onboard':'Open your business','type':'Business type','beauty':'Beauty professional','seller':'Fashion seller','both':'Beauty + fashion','businessName':'Business name','category':'Category','location':'Location','whatsapp':'WhatsApp number','bio':'Bio','continue':'Continue','services':'Services','addService':'Add service','addProduct':'Add product','price':'Price (CFA)','stock':'Stock','availability':'Availability','day':'Day','start':'Start','end':'End','slot':'Slot minutes','save':'Save','book':'Book','chooseTime':'Choose an available time','noSlots':'No available slots','pending':'Pending','confirmed':'Confirmed','completed':'Completed','cancelled':'Cancelled','markRead':'Mark read','payment':'Payment','payLater':'Pay later','mobileSoon':'Mobile Money coming soon','search':'Search','language':'Language','customer':'Customer','setupNeeded':'App configuration required','setupHelp':'Add SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY at build time.'},
    'fr':{'app':'BEAUTYBOOK','home':'Accueil','shop':'Boutique','bookings':'Réservations','sell':'Vendre','profile':'Profil','professionals':'Professionnels de beauté','fashion':'Marché de la mode','notifications':'Notifications','login':'Connexion','signup':'Créer un compte','email':'E-mail','password':'Mot de passe','logout':'Déconnexion','onboard':'Créer votre activité','type':'Type d’activité','beauty':'Professionnel de beauté','seller':'Vendeur de mode','both':'Beauté + mode','businessName':'Nom de l’activité','category':'Catégorie','location':'Localisation','whatsapp':'Numéro WhatsApp','bio':'Présentation','continue':'Continuer','services':'Services','addService':'Ajouter un service','addProduct':'Ajouter un produit','price':'Prix (CFA)','stock':'Stock','availability':'Disponibilités','day':'Jour','start':'Début','end':'Fin','slot':'Durée du créneau','save':'Enregistrer','book':'Réserver','chooseTime':'Choisissez une heure disponible','noSlots':'Aucun créneau disponible','pending':'En attente','confirmed':'Confirmée','completed':'Terminée','cancelled':'Annulée','markRead':'Marquer comme lu','payment':'Paiement','payLater':'Payer plus tard','mobileSoon':'Mobile Money bientôt disponible','search':'Rechercher','language':'Langue','customer':'Client','setupNeeded':'Configuration requise','setupHelp':'Ajoutez SUPABASE_URL et SUPABASE_PUBLISHABLE_KEY lors de la compilation.'}}
  ;
  String t(String k)=>_v[locale.languageCode]?[k]??_v['en']![k]??k;
}
